- name: Connect to docker-test-instance, install dependencies and run docker container
  hosts: all
  become: true
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - docker

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
  
    - name: Pull train-schedule image from dockerhub
      become: true
      command: docker pull bryanmartineze/train-schedule:latest
    - name: Run docker image
      become: true
      command: docker run -d -p 80:8080 bryanmartineze/train-schedule:latest