permissions:
  id-token: write
  #Was changed from read to write to create a checkout -b to gh-pahes
  contents: write

name: Deploy train schedule
on: 

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Set up Java 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Check Java version
      run: java -version
    - name: Setup Gradle and build
      run: |
          ./gradlew build
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zipped-bundle
        path: dist/trainSchedule.zip
    
          
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Download Artifact
       uses: actions/download-artifact@v2
       with:
        name: zipped-bundle
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh_actions_role_example_pipeline
        aws-region: us-east-1
     - name: Upload to S3
       run: aws s3 cp trainSchedule.zip s3://cicd-pipeline-example-artifacts/${{ github.repository }}/trainSchedule.zip
       
  test-on-terraform:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        working-directory: terraform
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        working-directory: terraform
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        working-directory: terraform
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
      - name: Terraform Plan Status
        working-directory: terraform
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

