permissions:
  id-token: write
  #Was changed from read to write to create a checkout -b to gh-pahes
  contents: write

name: Deploy train schedule
on: 

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Set up Java 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Check Java version
      run: java -version
    - name: Setup Gradle and build
      run: |
          ./gradlew build
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zipped-bundle
        path: dist/trainSchedule.zip
    
          
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Download Artifact
       uses: actions/download-artifact@v2
       with:
        name: zipped-bundle
    steps:
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh_actions_role_example_pipeline
        aws-region: us-east-1
     - name: Upload to S3
       run: aws s3 cp trainSchedule.zip s3://cicd-pipeline-example-artifacts/${{ github.repository }}/trainSchedule.zip